### ISSUE TITLE
Image Size Issue

### ISSUE THREAD

**Issue by hackie-me** [hkdevloper/ABC#42]
1	Images : Logo and tumbnail :- when user upload this it should auto crop max height : 250px
2	Images : gallery, products  and other images :- when user upload this it should auto crop max height : 640
3	User Image icon : round border color same as or button color

**Comment by KirruBokhani** [comment]
use ->resize(50) to compress 50% of Image original size.

**Comment by hackie-me** [comment]
@a2zgitta check image compression is made of 50% image size is reduced. 

Note: **To maintain size and image quality I have set this to 50% compression it can be more but then Image quality is very low**

**Comment by KirruBokhani** [comment]
@a2zgitta Currently check only in **_bisdir.hkdevs.tech_** and In Admin panel only later we will update everywhere.
